# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r dev-requiremnets.txt
        python -m pip install -e .
    - name: Test with pytest
      run: |
        # Run py.test as root, as we fuck around with setuid
        sudo $(which py.test) -vvv --cov=jupyterhub_inithooks  tests/
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
